### ISSUE TITLE
Sign the assembly (strong name)

### ISSUE THREAD

**Issue by Kyrodan** [goenning/SharpSapRfc#26]
I use your assembly in a project which requires strong names.
So please sign your assemblies in your NuGet packages.

**Comment by oenning** [comment]
Will do it as soon as I can.

**Comment by goenning** [comment]
Released v2.0.4 with signed assemblies.
Update your nuget and see if it works.

Regards,
Guilherme

**Comment by Kyrodan** [comment]
It works, thanks a lot.
