### ISSUE TITLE
Can't publish ASP.NET 5 with sapnco_utils.dll reference

### ISSUE THREAD

**Issue by skarta** [goenning/SharpSapRfc#31]
Hi

After referencing sapnco.dll and sapnco_utils.dll when i attempt to publish my asp.net 5 project I get the following error:

'The package ID 'sapnco_utils' contains invalid characters'...
 
I understand that this is due to the underscore in one of the the dll names.  Any thoughts or suggestions on getting around this much appreciated.

**Comment by goenning** [comment]
I don't think it is a problem with the assembly name.

Where did you get it from? Are they the same architecture as SharpSapRfc. 

Do you get this error on compiling or when you're running your App?

**Comment by skarta** [comment]
They're x86 from the SAP Service market Place.  The app builds and runs debugged through visual studio OK, it's only when publishing that this error sadly makes an appearance.  I think it's an issue to do with how asp.net 5 projects handle assembly references which has introduced this naming constraint.

**Comment by goenning** [comment]
Well, it seens is is really an issue with naming constraint (https://github.com/aspnet/Home/issues/874).
Unfortunately I don't know if I can do anything to help you. If you find a solution, please comment it.

Thanks!
