### ISSUE TITLE
Using IDestinationConfigur​ation instead of AppConfig parameters

### ISSUE THREAD

**Issue by f4i2u1** [goenning/SharpSapRfc#33]
Hi Guilherme,

First of all, I'd like to express my utmost thanks for creating SharpSapRfc on here. It helps to reduce my work a lot and surely it simplifies to a great extent in dealing with the the SAP .Net connector coding complexities. 

Please pardon my novice knowledge in the area but is it possible to use your package with our own SAP connection parameters created on the fly (instead of getting them from Appconfig file) by implementing the IDestinationConfiguration interface? 

Many thanks in advance and keep up the brilliant work!

Kind regards,
Faizul

**Comment by f4i2u1** [comment]
Forgot to mention that I'd like to know whetherit's possible that SoapSapRfcConnection could be used without having to read parameters from static config file as well. Cheers.

**Comment by goenning** [comment]
Hi f4i2u1,

You can achieve that by implementing your own `IDestinationConfiguration` class, this way you can set your parameters dynamically.

Take a look at this example.

```C#
public class Program
{
    public class CustomDestinationConfig : IDestinationConfiguration
    {
        public object ConfigurationManager { get; private set; }

        public bool ChangeEventsSupported()
        {
            return false;
        }

        public event RfcDestinationManager.ConfigurationChangeHandler ConfigurationChanged;

        public RfcConfigParameters GetParameters(string destinationName)
        {
            if (destinationName == "MY_CUSTOM_CONN")
            {
                RfcConfigParameters parms = new RfcConfigParameters();
                parms.Add(RfcConfigParameters.Name, "MY_CUSTOM_CONN");
                parms.Add(RfcConfigParameters.AppServerHost, "yourserver.com");
                parms.Add(RfcConfigParameters.SystemNumber, "00");
                parms.Add(RfcConfigParameters.SystemID, "ECC");
                parms.Add(RfcConfigParameters.User, "user");
                parms.Add(RfcConfigParameters.Password, "p$ss");
                parms.Add(RfcConfigParameters.Client, "100");
                return parms;
            }
            else
                throw new ArgumentOutOfRangeException(destinationName);
        }
    }

    public static void Main(string[] args)
    {
        RfcDestinationManager.RegisterDestinationConfiguration(new CustomDestinationConfig());

        using (SapRfcConnection conn = new PlainSapRfcConnection("MY_CUSTOM_CONN"))
        {
            var result = conn.ExecuteFunction("Z_SSRT_SUM",
                new RfcParameter("i_num1", 2),
                new RfcParameter("i_num2", 4)
            );

            var total = result.GetOutput<int>("e_result");
        }
    }
}
```

**Comment by goenning** [comment]
Regarding dynamic configuration with `SoapSapRfcConnection`, unfortunately it is not possible. That was something I didn't think about. 

I will put this on my schedule and release a minor update (2.0.9) with this feature, it should be easy to implement.

**Comment by f4i2u1** [comment]
Many thanks and looking forward for the minor update!

**Comment by goenning** [comment]
Ok, it's done, you can take a look at this test case [1] for an example.
I'm planning to push v2.0.9 to NuGet before Friday.

[1] [ConnectionTestCase.cs](https://github.com/goenning/SharpSapRfc/blob/bb241cf1e2117d1a94af8c6f8bb825b654ba1bfa/tests/TestCases/ConnectionTestCase.cs)

**Comment by f4i2u1** [comment]
Excellent! Many thanks for the help and quick turnaround, really appreciate
it!

Kind regards,
Faizul
