### ISSUE TITLE
META tag errors when submitting invalid logon parameters via SOAP

### ISSUE THREAD

**Issue by f4i2u1** [goenning/SharpSapRfc#34]
Hi Guilherme,

I noticed that when passing invalid logon parameters (wrong password, invalid client number, invalid username) using the soap connection, errors are returned in the form of "The META start tag on line X position XX does not match the end of tag of 'head'.." instead of returning meaningful errors e.g. access denied etc. Is it possible to make the library to return meaningful errors re. invalid parameters passed? I also noticed that the NetWeaver actually returned http access denied error to web client instead of passing a proper xml error response, but I haven't gone further on this though to be 100 pct sure. Many thanks and keep up the good work!

Kind regards,
Faizul

**Comment by goenning** [comment]
I'll look into it as soon as I can. Thanks for your input.
