### ISSUE TITLE
SapRfcConnection.ReadTable returns "object reference not set to an instance of an object" when missing authorizations

### ISSUE THREAD

**Issue by f4i2u1** [goenning/SharpSapRfc#36]
Hi Guilherme,

Noticed that the SapRfcConnection.ReadTable returns "object reference not set to an instance of an object" whenever SAP server detects that the user id  doesn't have the correct permission to execute RFC (such as missing S_RFC object field RFC_NAME=RFC_METADATA or RFC_NAME=SDTX authorizations). Would be great if a more meaningful error is returned by the method such as "Missing authorizations" instead.

Many thanks!

Kind regards,
Faizul

**Comment by goenning** [comment]
Does it also happens when calling `ExecuteFunction` or the problem is only with `ReadTable`?

**Comment by f4i2u1** [comment]
Not sure as I'm only using `ReadTable` for my app at the moment.

**Comment by f4i2u1** [comment]
Hi Guilherme,

Any chance of getting this update anytime soon? Many thanks..

**Comment by goenning** [comment]
Hi, it's not on my schedule. Would be happy to receive some pull requests on this.

**Comment by goenning** [comment]
Hi Faizul,

Thanks for you pull.
I've made some changes to it and added unit tests.

v2.0.10 is available at NuGet. Can you please ensure it's working for you?

👍

**Comment by f4i2u1** [comment]
Hi Gulherme,

Excellent! Error messages are better now. You closed all my reported bugs. Many thanks.
