### ISSUE TITLE
X64 Version

### ISSUE THREAD

**Issue by KaiserSozei87** [goenning/SharpSapRfc#43]
Is there a X64 version of this package, the .plain package is x64 but has a dependency on the SharSapRFC package which has a x32 DLL?

**Comment by goenning** [comment]
Hi,

The x64 package is `SharpSapRfc.Plain.x64`, but `SharSapRfc` is not CPU specific.

**Comment by KaiserSozei87** [comment]
Hhmmm I must have went wrong somewhere then, when I attempt to install just the plain.x64 it automatically gets the SharpSapRfc package as a dependency, when looking at the DLL in the packages folder using dumpbin it is a x86 file. I'll take another look tomorrow and see if I can it running with just the plain.x64 package. 

As a side note are there any plans to port this to .NET core?

**Comment by goenning** [comment]
Please double check it, but I wouldn't be surprised if It's actually wrong as I may have messed up the binaries before publishing to NuGet :)

This package would be rather easy to port to .NET Core, but it has a strong dependency on SAPNCo, which is developed by SAP, so there are no plans for now.

**Comment by KaiserSozei87** [comment]
Thanks for the reply :)

**Comment by KaiserSozei87** [comment]
I'm still not sure this is working just as an FYI
